require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@4.3.0_@capacitor+core@4.3.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@4.3.0_@capacitor+core@4.3.0/node_modules/@capacitor/ios'
  pod 'AparajitaCapacitorDarkMode', :path => '../../node_modules/.pnpm/@aparajita+capacitor-dark-mode@3.0.3/node_modules/@aparajita/capacitor-dark-mode'
  pod 'AparajitaCapacitorLogger', :path => '../../node_modules/.pnpm/@aparajita+capacitor-logger@3.1.1_@capacitor+core@4.3.0/node_modules/@aparajita/capacitor-logger'
  pod 'AparajitaCapacitorSplashScreen', :path => '../../node_modules/.pnpm/@aparajita+capacitor-splash-screen@2.0.0/node_modules/@aparajita/capacitor-splash-screen'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@4.0.1_@capacitor+core@4.3.0/node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../node_modules/.pnpm/@capacitor+haptics@4.0.1_@capacitor+core@4.3.0/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.pnpm/@capacitor+keyboard@4.0.1_@capacitor+core@4.3.0/node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../node_modules/.pnpm/@capacitor+status-bar@4.0.1_@capacitor+core@4.3.0/node_modules/@capacitor/status-bar'
end

target 'SplashScreenDemo' do
  capacitor_pods
  # Add your Pods here
end


post_install do |installer|
  assertDeploymentTarget(installer)
end
